package com.mycompany.actividad1.adapter;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class OracleDatabaseAdapter implements DatabaseAdapter {
    private final String url;
    private final String user;
    private final String password;

    public OracleDatabaseAdapter(String url, String user, String password) {
        this.url = url;
        this.user = user;
        this.password = password;
    }

    @Override
    public Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    @Override
    public void initDatabase() {
        try (Connection conn = getConnection(); 
             Statement stmt = conn.createStatement()) {
            
            // Crear tablas específicas para Oracle
            stmt.execute("CREATE TABLE PERSONA (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "nombre VARCHAR2(255), " +
                        "edad NUMBER)");
                        
            stmt.execute("CREATE TABLE FACULTAD (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "nombre VARCHAR2(255), " +
                        "ubicacion VARCHAR2(255))");
                        
            stmt.execute("CREATE TABLE PROGRAMA (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "nombre VARCHAR2(255), " +
                        "facultad_id NUMBER, " +
                        "CONSTRAINT fk_programa_facultad FOREIGN KEY (facultad_id) REFERENCES FACULTAD(id))");
                        
            stmt.execute("CREATE TABLE PROFESOR (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "persona_id NUMBER, " +
                        "especialidad VARCHAR2(255), " +
                        "CONSTRAINT fk_profesor_persona FOREIGN KEY (persona_id) REFERENCES PERSONA(id))");
                        
            stmt.execute("CREATE TABLE ESTUDIANTE (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "persona_id NUMBER, " +
                        "programa_id NUMBER, " +
                        "semestre NUMBER, " +
                        "CONSTRAINT fk_estudiante_persona FOREIGN KEY (persona_id) REFERENCES PERSONA(id), " +
                        "CONSTRAINT fk_estudiante_programa FOREIGN KEY (programa_id) REFERENCES PROGRAMA(id))");
                        
            stmt.execute("CREATE TABLE CURSO (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "nombre VARCHAR2(255), " +
                        "creditos NUMBER, " +
                        "programa_id NUMBER, " +
                        "CONSTRAINT fk_curso_programa FOREIGN KEY (programa_id) REFERENCES PROGRAMA(id))");
                        
            stmt.execute("CREATE TABLE INSCRIPCION (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "estudiante_id NUMBER, " +
                        "curso_id NUMBER, " +
                        "fecha_inscripcion DATE, " +
                        "CONSTRAINT fk_inscripcion_estudiante FOREIGN KEY (estudiante_id) REFERENCES ESTUDIANTE(id), " +
                        "CONSTRAINT fk_inscripcion_curso FOREIGN KEY (curso_id) REFERENCES CURSO(id))");
                        
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public String getDatabaseType() {
        return "Oracle";
    }
}
